apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30007
