#apiVersion: v1
#kind: Service
#metadata:
#  name: ticket-app-service
#spec:
#  selector:
#    app: ticket-app
#  ports:
#    - protocol: TCP
#      port: 8081
#      targetPort: 8081
#  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: ticket-app-service
spec:
  selector:
    app: ticket-app
  ports:
    - protocol: TCP
      port: 8081 #у богдана 8080
      targetPort: 8081 #у богдана 8080
  type: LoadBalancer
